/* AUTO-GENERATED by design-tokens/build-tokens.mjs. Do not edit directly. */

export const tokens = {
  "light": {
    "colors": {
      "background": "#ffffff",
      "foreground": "#0a0a0a",
      "card": "#ffffff",
      "cardForeground": "#0a0a0a",
      "popover": "#ffffff",
      "popoverForeground": "#0a0a0a",
      "primary": "#171717",
      "primaryForeground": "#fafafa",
      "secondary": "#eeeeee",
      "secondaryForeground": "#171717",
      "muted": "#f5f5f5",
      "mutedForeground": "#737373",
      "accent": "#eeeeee",
      "accentForeground": "#171717",
      "destructive": "#9a704b",
      "destructiveForeground": "#ffffff",
      "success": "#647567",
      "successForeground": "#ffffff",
      "border": "#d6d6d6",
      "input": "#e4e4e4",
      "ring": "#a1a1a1",
      "chart1": "#ac8653",
      "chart2": "#728487",
      "chart3": "#3f495a",
      "chart4": "#d6c27b",
      "chart5": "#c8ae6d",
      "sidebar": "#fbfbfb",
      "sidebarForeground": "#0a0a0a",
      "sidebarPrimary": "#171717",
      "sidebarPrimaryForeground": "#fafafa",
      "sidebarAccent": "#f5f5f5",
      "sidebarAccentForeground": "#171717",
      "sidebarBorder": "#e5e5e5",
      "sidebarRing": "#a1a1a1",
      "codeBackground": "#fafafa",
      "codeForeground": "#0a0a0a"
    },
    "radius": {
      "sm": 6,
      "md": 8,
      "lg": 10,
      "xl": 14
    },
    "typography": {
      "fontSans": "Inter",
      "fontMono": "JetBrainsMono"
    }
  },
  "dark": {
    "colors": {
      "background": "#0d0d0d",
      "foreground": "#fafafa",
      "card": "#171717",
      "cardForeground": "#fafafa",
      "popover": "#171717",
      "popoverForeground": "#fafafa",
      "primary": "#e5e5e5",
      "primaryForeground": "#171717",
      "secondary": "#2b2b2b",
      "secondaryForeground": "#fafafa",
      "muted": "#262626",
      "mutedForeground": "#a1a1a1",
      "accent": "#262626",
      "accentForeground": "#fafafa",
      "destructive": "#ba987f",
      "destructiveForeground": "#fafafa",
      "success": "#95a899",
      "successForeground": "#060606",
      "border": "rgba(255, 255, 255, 0.300)",
      "input": "rgba(255, 255, 255, 0.300)",
      "ring": "#737373",
      "chart1": "#4f65be",
      "chart2": "#8da18d",
      "chart3": "#c8ae6d",
      "chart4": "#8b88dd",
      "chart5": "#af856d",
      "sidebar": "#141414",
      "sidebarForeground": "#fafafa",
      "sidebarPrimary": "#4f65be",
      "sidebarPrimaryForeground": "#fafafa",
      "sidebarAccent": "#262626",
      "sidebarAccentForeground": "#fafafa",
      "sidebarBorder": "rgba(255, 255, 255, 0.100)",
      "sidebarRing": "#737373",
      "codeBackground": "#1c1c1c",
      "codeForeground": "#d6d6d6"
    },
    "radius": {
      "sm": 6,
      "md": 8,
      "lg": 10,
      "xl": 14
    },
    "typography": {
      "fontSans": "Inter",
      "fontMono": "JetBrainsMono"
    }
  }
} as const;

export type ThemeMode = keyof typeof tokens;
export type ThemeTokens = (typeof tokens)[ThemeMode];
