/* AUTO-GENERATED by control-plane/scripts/bundle-skill-catalog.mjs — DO NOT EDIT.
 *
 * Source of truth: skills/meta/<name>/SKILL.md
 * Regenerate: node control-plane/scripts/bundle-skill-catalog.mjs
 *
 * Phase 7 commit 7.2a: meta-agent-only skill bodies, consumed by
 * the control-plane prompt builder (meta-agent-chat.ts). Keys are
 * the SKILL.md parent directory name; values are the raw body with
 * exactly one trailing newline trimmed.
 */

export const META_SKILL_BODIES: Record<string, string> = {
};
