/* AUTO-GENERATED by control-plane/scripts/bundle-skill-catalog.mjs — DO NOT EDIT.
 *
 * Source of truth: skills/public/<name>/SKILL.md
 * Regenerate: node control-plane/scripts/bundle-skill-catalog.mjs
 *
 * Emits metadata ONLY (name, description, when_to_use, min_plan,
 * delegate_agent). Full prompt_template bodies live in
 * deploy/src/runtime/skills-manifest.generated.ts for the edge worker.
 */

export interface SkillCatalogEntry {
  name: string;
  description: string;
  when_to_use?: string;
  min_plan?: "basic" | "standard" | "premium";
  delegate_agent?: string;
}

export const SKILL_CATALOG: SkillCatalogEntry[] = [
  {"name":"analyze","description":"Analyze data files (CSV, JSON, Excel) — clean, summarize, find patterns, and generate insights.","when_to_use":"When the user provides or references data and asks for analysis, insights, trends, patterns, statistics, or summaries.","min_plan":"standard","delegate_agent":"data-analyst"},
  {"name":"batch","description":"Decompose a large task into independent sub-tasks and execute them in parallel via delegated agents.","when_to_use":"When the user has a large task that can be decomposed into independent parallel sub-tasks, or explicitly asks to batch/parallelize work."},
  {"name":"build-app","description":"Build a complete application — plan, scaffold, implement, test. Covers CLI tools, APIs, scripts, data pipelines, and general TypeScript/Python projects. For web apps and websites, prefer the /website skill.","when_to_use":"When the user asks to build an app, tool, script, API, CLI, pipeline, or any non-web project. Also when the user says 'build me' something without specifying web."},
  {"name":"chart","description":"Generate publication-quality charts, graphs, and data visualizations using Python.","when_to_use":"When the user asks to create a chart, graph, plot, visualization, or visual representation of data.","min_plan":"standard","delegate_agent":"data-analyst"},
  {"name":"code-review","description":"Structured code review with security, performance, and maintainability checks"},
  {"name":"debug","description":"Diagnose issues with the current agent: check error rates, circuit breaker status, recent failures, and tool health.","when_to_use":"When the user reports an error, asks why something is broken, or needs help diagnosing agent or tool failures."},
  {"name":"deep-research","description":"Systematic multi-angle research methodology for thorough investigation"},
  {"name":"design","description":"Apply professional design foundations — color palettes, typography, data visualization rules, accessibility standards. Use when creating any visual output.","when_to_use":"When the user asks to design something visual, choose colors, create a palette, select typography, or needs design guidance for any output format (web, PDF, slides, charts)."},
  {"name":"diarize","description":"Structured cross-source profile (SAYS / ACTUALLY DOES / CHANGED / CONTRADICTIONS) for one subject across multiple sources"},
  {"name":"docs","description":"Load relevant API documentation, SDK reference, or framework guides based on the current project context."},
  {"name":"docx","description":"Create, edit, and convert Word documents (.docx). Supports creation from scratch, template editing, PDF-to-Word conversion, and text extraction.","when_to_use":"When the user asks to create, edit, convert, or extract text from a Word document, .docx file, or asks for a formatted document output."},
  {"name":"game","description":"Build a browser game — 2D Canvas or 3D WebGL with Three.js. Covers game loop, physics, input, audio, and deployment.","when_to_use":"When the user asks to build a browser game, 2D game, 3D game, or interactive game experience."},
  {"name":"improve","description":"Analyze feedback on a target skill, extract recurring failure patterns, and propose rules to append via manage_skills append_rule"},
  {"name":"pdf","description":"Create, read, extract, or fill PDF documents. Supports text extraction, table extraction, PDF generation, and form filling.","when_to_use":"When the user asks to create, read, extract text from, merge, split, fill forms in, or convert a PDF document.","min_plan":"standard","delegate_agent":"pdf-specialist"},
  {"name":"pptx","description":"Create and edit PowerPoint presentations (.pptx). Professional slide design with data visualization, layout variety, and consistent typography.","when_to_use":"When the user asks to create, edit, or design a PowerPoint presentation, slide deck, or .pptx file."},
  {"name":"remember","description":"Review and curate the agent's memory: deduplicate facts, promote useful patterns to procedural memory, clean stale entries.","when_to_use":"When the user asks to clean up, deduplicate, or curate the agent's memory."},
  {"name":"report","description":"Generate a structured markdown research report with citations, data visualizations, and executive summary.","when_to_use":"When the user asks for a written report, white paper, briefing document, research summary, or any structured deliverable with citations and analysis.","min_plan":"standard","delegate_agent":"research-analyst"},
  {"name":"research","description":"Deep iterative research with multi-source evidence gathering, cross-referencing, and structured synthesis.","when_to_use":"When the user asks a question requiring investigation, fact-checking, market analysis, competitive analysis, or any query that benefits from searching multiple sources and synthesizing findings with citations.","min_plan":"standard","delegate_agent":"research-analyst"},
  {"name":"review","description":"Review changed code through 3 parallel lenses: reuse, quality, and efficiency. Then fix found issues.","when_to_use":"When the user asks to review code changes, check code quality, audit recent commits, or do a code review."},
  {"name":"schedule","description":"Schedule an agent to run a task on a recurring interval (e.g., 'every morning at 9am check for new issues')."},
  {"name":"skillify","description":"Extract a repeatable process from this conversation into a reusable skill definition."},
  {"name":"spreadsheet","description":"Create or analyze Excel spreadsheets with formulas, formatting, charts, and data analysis.","when_to_use":"When the user asks to create, edit, or analyze an Excel spreadsheet, .xlsx file, or asks for data in spreadsheet format with formatting.","min_plan":"standard","delegate_agent":"data-analyst"},
  {"name":"verify","description":"Verify that a change works by running the agent's eval test cases against it.","when_to_use":"When the user asks to verify a change works, run tests, or check for regressions."},
  {"name":"website","description":"Build a complete website or web app — design, code, and test. Covers landing pages, portfolios, web apps, and browser games.","when_to_use":"When the user asks to build a website, web app, landing page, portfolio site, or any web-based project."},
];

export const SKILL_CATALOG_BY_NAME: Record<string, SkillCatalogEntry> =
  Object.fromEntries(SKILL_CATALOG.map((s) => [s.name, s]));

/** Lean allowlist for meta-agent validation: just the set of names. */
export const SKILL_CATALOG_NAMES: ReadonlySet<string> =
  new Set(SKILL_CATALOG.map((s) => s.name));
