import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const sourcePath = resolve(__dirname, "tokens.json");
const outCssPath = resolve(ROOT, "ui/src/generated/tokens.css");
const outRnPath = resolve(ROOT, "mobile/src/theme/tokens.ts");

const source = JSON.parse(readFileSync(sourcePath, "utf8"));

function parseOklch(oklch) {
  const match = oklch.trim().match(/^oklch\((.+)\)$/i);
  if (!match) throw new Error(`Unsupported color format: ${oklch}`);
  const raw = match[1].trim();
  const [basePart, alphaPart] = raw.split("/").map((s) => s.trim());
  const base = basePart.split(/\s+/).map(Number);
  if (base.length < 2) throw new Error(`Invalid OKLCH: ${oklch}`);

  let l = base[0];
  if (l > 1) l /= 100;
  const c = base[1];
  const h = base.length >= 3 ? base[2] : 0;

  let alpha = 1;
  if (alphaPart) {
    alpha = alphaPart.endsWith("%")
      ? Number(alphaPart.replace("%", "")) / 100
      : Number(alphaPart);
  }
  alpha = clamp(alpha, 0, 1);
  return { l, c, h, alpha };
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function linearToSrgb(v) {
  if (v <= 0.0031308) return 12.92 * v;
  return 1.055 * Math.pow(v, 1 / 2.4) - 0.055;
}

function oklchToRgbaString(oklch) {
  const { l, c, h, alpha } = parseOklch(oklch);
  const hr = (h * Math.PI) / 180;
  const a = c * Math.cos(hr);
  const b = c * Math.sin(hr);

  const l_ = l + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = l - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = l - 0.0894841775 * a - 1.291485548 * b;

  const l3 = l_ ** 3;
  const m3 = m_ ** 3;
  const s3 = s_ ** 3;

  const x = +0.4122214708 * l3 + 0.5363325363 * m3 + 0.0514459929 * s3;
  const y = +0.2119034982 * l3 + 0.6806995451 * m3 + 0.1073969566 * s3;
  const z = +0.0883024619 * l3 + 0.2817188376 * m3 + 0.6299787005 * s3;

  const rLin = +4.0767416621 * x - 3.3077115913 * y + 0.2309699292 * z;
  const gLin = -1.2684380046 * x + 2.6097574011 * y - 0.3413193965 * z;
  const bLin = -0.0041960863 * x - 0.7034186147 * y + 1.707614701 * z;

  const r = Math.round(clamp(linearToSrgb(rLin), 0, 1) * 255);
  const g = Math.round(clamp(linearToSrgb(gLin), 0, 1) * 255);
  const b2 = Math.round(clamp(linearToSrgb(bLin), 0, 1) * 255);

  return alpha < 1 ? `rgba(${r}, ${g}, ${b2}, ${alpha.toFixed(3)})` : `#${toHex(r)}${toHex(g)}${toHex(b2)}`;
}

function toHex(v) {
  return v.toString(16).padStart(2, "0");
}

function toCamel(kebab) {
  return kebab.replace(/-([a-z0-9])/g, (_, m) => m.toUpperCase());
}

function buildCss() {
  const lines = [
    "/* AUTO-GENERATED by design-tokens/build-tokens.mjs. Do not edit directly. */",
    "",
    ":root {",
    `  --radius: ${source.radius.base};`,
    `  --font-sans: ${source.typography["font-sans"]};`,
    `  --font-mono: ${source.typography["font-mono"]};`,
  ];

  for (const [name, pair] of Object.entries(source.colors)) {
    lines.push(`  --${name}: ${pair.light};`);
  }
  lines.push("}", "", ".dark {");
  for (const [name, pair] of Object.entries(source.colors)) {
    lines.push(`  --${name}: ${pair.dark};`);
  }
  lines.push("}", "");

  return lines.join("\n");
}

function buildReactNativeTs() {
  const lightColors = {};
  const darkColors = {};
  for (const [name, pair] of Object.entries(source.colors)) {
    lightColors[toCamel(name)] = oklchToRgbaString(pair.light);
    darkColors[toCamel(name)] = oklchToRgbaString(pair.dark);
  }

  const rn = {
    light: {
      colors: lightColors,
      radius: source.radius.mobile,
      typography: {
        fontSans: source.typography.mobileFontSans,
        fontMono: source.typography.mobileFontMono,
      },
    },
    dark: {
      colors: darkColors,
      radius: source.radius.mobile,
      typography: {
        fontSans: source.typography.mobileFontSans,
        fontMono: source.typography.mobileFontMono,
      },
    },
  };

  return [
    "/* AUTO-GENERATED by design-tokens/build-tokens.mjs. Do not edit directly. */",
    "",
    `export const tokens = ${JSON.stringify(rn, null, 2)} as const;`,
    "",
    "export type ThemeMode = keyof typeof tokens;",
    "export type ThemeTokens = (typeof tokens)[ThemeMode];",
    "",
  ].join("\n");
}

function writeFile(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf8");
}

writeFile(outCssPath, buildCss());
writeFile(outRnPath, buildReactNativeTs());

console.log(`Generated:\n- ${outCssPath}\n- ${outRnPath}`);
