/**
 * OpenAPI routes — serves the auto-generated spec + Scalar docs.
 *
 * The actual OpenAPI spec is auto-generated by OpenAPIHono in index.ts
 * at /api/v1/openapi.json. This file provides the public-facing /v1 aliases
 * for backwards compatibility.
 */
import { createRoute, z } from "@hono/zod-openapi";
import { createOpenAPIRouter } from "../lib/openapi";

export const openapiRoutes = createOpenAPIRouter();

// ── GET /openapi.json — redirect to auto-generated spec ────────────────

const specRoute = createRoute({
  method: "get",
  path: "/openapi.json",
  tags: ["System"],
  summary: "OpenAPI 3.1 specification",
  security: [],
  responses: {
    302: { description: "Redirect to auto-generated spec" },
  },
});

openapiRoutes.openapi(specRoute, (c): any => {
  return c.redirect("/api/v1/openapi.json", 302);
});

// ── GET /docs — Scalar API reference UI ─────────────────────────────────

const docsRoute = createRoute({
  method: "get",
  path: "/docs",
  tags: ["System"],
  summary: "Interactive API documentation",
  security: [],
  responses: {
    200: { description: "HTML documentation page" },
  },
});

openapiRoutes.openapi(docsRoute, (c): any => {
  const html = `<!DOCTYPE html>
<html>
<head>
  <title>AgentOS API Reference</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <script id="api-reference" data-url="/api/v1/openapi.json"></script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
</html>`;
  return c.html(html);
});
