$kind: http-request
name: Get Deploy Status
method: GET
url: '{{base_url}}/api/v1/deploy/{{agent_name}}/status'
order: 3000
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{api_token}}'
pathVariables:
  - key: agent_name
    value: '{{agent_name}}'
